### PR TITLE
Feat[SOL-111048]: Added a new publisher and subscriber sample to demonstrate otel tracing using the Solace PubSub+ Go APIs

### PR DESCRIPTION
**Pull request by oodigie**
The goal is to add a Otel publisher and subscriber samples to demonstrate tracing using the Solace PubSub+ Go APIs.

**Changes:**
- Added a new publisher and subscriber sample to demonstrate OTel tracing using the Solace PubSub+ Go APIs (the PubSub+ Go Client and the PubSub+ Integration API).
- Updated the go.mod file to include the required dependencies for the OTel samples.
- Renamed the import path for the PubSub+ Go Integration API to match the updated package root
- Bumped up the version of the PubSub+ Go Client API from `1.4.0` to the latest `1.5.0`

### CODE REVIEW

**Comment by oodigie** [comment]
As the Otel tracing feature for the PubSub+ Go APIs has not be released, this would be a draft-pull-request so it is not accidentally merged before then.

**Comment by TamimiGitHub** [comment]
Note to self: https://github.com/SolaceDev/solace-dev/pull/171 should be merged first before testing

**Comment by klaus-ziegert** [comment]
Can it be done with v1.5.0 now? An example would be really helpful!

**Comment by TamimiGitHub** [comment]
Tested out the publisher and subscriber - looks good, thanks @oodigie ! 

@klaus-ziegert - the api is now released! feel free to use it, and if you have any question dont hesitate to ask here or on the [Solace Community](https://solace.community/)

**Review by TamimiGitHub — APPROVED** [review]

**Pull request merged**
